# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('password', models.CharField(max_length=40, verbose_name='password')),
                ('c_password', models.CharField(max_length=40, verbose_name='confirm password')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
