# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('instructor', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField(blank=True)),
                ('syllabus', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('contact_person', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(max_length=255, unique=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='cprovider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.CourseProvider'),
        ),
    ]
